spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootdemo?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler  # 设置默认enum类型处理器：使用ordinal序数
    map-underscore-to-camel-case: true  # db的下划线字段转驼峰命名

  # 类型处理器所在包
  type-handlers-package: top.youngcoding.bootbatis.typehandler.anno.handler
